### ISSUE TITLE
I have find a Reflected XSS vulnerability in this project

### ISSUE THREAD

**Issue by jgj212** [Gargaj/wuhu#20]
Hello:
I have find a Reflected XSS vulnerability in this project.

The vulnerability exists due to insufficient filtration of user-supplied data in “id” HTTP parameter that will be passed to “wuhu-master/www_admin/users.php”. The infected source code is line 67, there is no protection on $_GET["id"]; if $_GET["id"] contains evil js code, line 67 will trigger untrusted code to be excuted on the browser side.
![code1](https://cloud.githubusercontent.com/assets/1484292/23576388/e82ff782-00de-11e7-8155-295640d2a39a.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/wuhu-master/www_admin/users.php?id="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 spq x64 + firefox 51.0.1 32bit ):
![sc](https://cloud.githubusercontent.com/assets/1484292/23576386/cc292b4e-00de-11e7-9967-51d7582decd4.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech

**Comment by Gargaj** [comment]
That's very nice but it's the admin interface, if you wanna break your own party, it's your own damn fault.

**Comment by jgj212** [comment]
@Gargaj yes, it is the admin interface. but a attacker can use this vulnerability to do some harm, because send a evil url  to the admin of the website do not need any admin permission.

**Comment by Gargaj** [comment]
It's not a website, it's a locally ran web interface, where the admin section is password protected and noone can send requests to it. But don't worry, i'll "fix" it.

**Comment by jgj212** [comment]
@Gargaj  tks, i got it

**Comment by attritionorg** [comment]
https://www.owasp.org/index.php/Testing_for_Reflected_Cross_site_scripting_(OTG-INPVAL-001) 

FYI
