### ISSUE TITLE
Consider FriendUP integration?

### ISSUE THREAD

**Issue by titlestad** [Gargaj/wuhu#23]
Hey! We displayed our project on Solskogen a couple of years back. Think it was back in 2016. When I saw your interface and how we interacted on the party, I thought, hey, our system would be great in that setting. Drag & drop to upload stuff to our cloud desktop. Etc.
FriendUP is open source - so you could host it on the party. Share live links. There's video / audio and IM chat. IRC. Everything needed for a party really.

Web apps are easily turned into Friend apps, complete with icons and a dock. So you can easily autostart the app on the Friend desktop on login.

Check us out on: https://github.com/FriendSoftwareLabs/friendup

Give me a shout if you're interested for this year's event.

**Comment by Gargaj** [comment]
This is probably out of our scope.
