### ISSUE TITLE
Platform field for production slides

### ISSUE THREAD

**Issue by glennlunder** [Gargaj/wuhu#28]
As discussed by the Solskogen crew after the most recent iteration of the party, it would be very nice to have a platform / production type field to show on the slides, in the cases where the user has submitted very sparse information and it sort-of matters what platform/limitation a given production has.

We've seen this successfully implemented in other party systems, and it would be very nice to have in Wuhu as well.

**Comment by Gargaj** [comment]
I have a conceptual problem with this: one of the basic tenets of Wuhu is that it treats compos (and subsequently entries) as completely agnostic from each other. "Platform" fields would only work if 1. there would be presets for compo types which would go against the above stated goal (i.e. you shouldn't have platforms for a streaming music compo) or 2. would leave it up to the organizers to fill the fields which they would inevitably not do.

If it is a common problem, my solution would be just to expand the text around the submission box on the user side to remind them to add the information to the comment field.

**Comment by glennlunder** [comment]
I agree with 1) completely, the specific use case we were thinking was instances where for instance the 4K and 64K compos get merged, or where a single entry in a different compo gets moved to Wild, for instance. Or just Wild in general, where a lot of esoteric hardware often comes into play. If, say, someone made a 4k procedural graphics entry and it got moved to Wild, then that'd be relevant data for the user to know - that this is indeed a 4k procedural graphics entry, and not a video. Also for oldskool demo competitions this comes into play, as there are often fundamental differences between the different platforms, and having a field for that would make sense (to us).

**Comment by Gargaj** [comment]
That does happen, however I'd argue since the merge usually happens post-deadline when all the entries are in and the organizers have to make the call, it's also up to the organizers to decide if they want to update the slides in such a situation :) (In which case they might as well do it with the comment field.)

**Comment by glennlunder** [comment]
As I see no interest from devs in implementing this, it makes little sense to keep the ticket open.

**Comment by Gargaj** [comment]
I thought there was a good discussion being had...? Also a note: there is nothing stopping a party who needs this to create a plugin without having to touch the main code tree.
