### ISSUE TITLE
Cannot set admin

### ISSUE THREAD

**Issue by reiven** [Gargaj/wuhu#41]
Hi! 
I've tried both install in a server or Dockerfile on a clean services, on Debian and every time i try to save the initial settings i got this error:

`PHP Fatal error:  Uncaught Error: Cannot access protected property SQLLib::$link in /var/www/www
_admin/config.php:138\nStack trace:\n#0 /var/www/www_admin/config.php(245): perform('')\n#1 {main}\n  thrown in /var/www/www_admin/config.php on line 138, referer: http://localho
st:8090/`

Also tried using nginx or apache

**Comment by Gargaj** [comment]
Can you try https://github.com/Gargaj/wuhu/commit/98338528bd144954fcc4ce66c4ffc944bcddd3be ?

**Comment by reiven** [comment]
Great!!! First time i see this 

![image](https://user-images.githubusercontent.com/362717/80493090-51ff8f00-893b-11ea-8ac6-631a3045d285.png)

Thanks @Gargaj
