### ISSUE TITLE
options to fit with black borders vs crop screenshots

### ISSUE THREAD

**Issue by psenough** [Gargaj/wuhu#54]
when submitting prods a few minutes before deadline most folks don't bother with opening an image editor to prepare a proper screenshot. a lot of the screenshots submitted end up getting badly cropped (especially graphic images in portrait mode). would be nice to have an option available to customize the uploaded screenshot a bit more, either to allowed the user to select the region or toggle on/off a fit vs crop setting.

**Comment by Gargaj** [comment]
Thumbnails are cropped; you can click on them for the uncropped version.

**Comment by psenough** [comment]
it had weird behavior with lovebyte's pixelgraphics compo (images could be 16x16, 12x21, 8x32), the crop would be only a portion of the image, and the uncropped version would be way too small (and if you tried to enlarge it by zooming the browser the browser would do their crappy aliasing). so it became quite hard to vote unless people had prepared a proper screenshot version which ofcourse most artists didn't submit.
