### ISSUE TITLE
slide editor: generate thumbnail

### ISSUE THREAD

**Issue by 0b5vr** [Gargaj/wuhu#75]
We're running wuhu on a potato machine (Google Cloud e2-micro 😅)
Loading the slide list on admin `/slideeditor.php` takes a lot of machine / network resources.

As we do for compo entries, if we can generate thumbnails for each slide it would be very nice.

**Comment by Gargaj** [comment]
Feels like an edge case situation where generating thumbnails would only affect that one page.

**Comment by 0b5vr** [comment]
> Feels like an edge case situation where generating thumbnails would only affect that one page.

...yeahhh. But the one page can take like 20~ MB of the bandwidth, and I often use that page.

The question is, would you mind if I implemented it as a plugin?

**Comment by Gargaj** [comment]
Sure, but it's an edge-enough case where I don't see the benefit of merging it to mainline. If you need new hooks, I'd be happy to have those though.

**Comment by 0b5vr** [comment]
Got it. It's not fatal/critical for us either, I'll wait till another sample of the request.
