### ISSUE TITLE
Deployment Fails: Uncaught ArgumentCountError: mysqli_connect_errno() expects exactly 0 arguments, 1 given

### ISSUE THREAD

**Issue by Bombe** [Gargaj/wuhu#76]
I set up a docker image with PHP 8 and MySQL 8, hit the “Deploy!” button and was greeted with this error message:
```
Uncaught ArgumentCountError: mysqli_connect_errno() expects exactly 0 arguments, 1 given in /var/www/html/www_admin/sqllib.inc.php:33
Stack trace:
#0 /var/www/html/www_admin/sqllib.inc.php(33): mysqli_connect_errno(Object(mysqli))
#1 /var/www/html/www_admin/config.php(140): SQLLib::Connect('wuhu-database-1', 'wuhu', 'wuhu', 'wuhu')
#2 /var/www/html/www_admin/config.php(233): perform('')
#3 {main}
```
According to the [documentation on php.net](https://www.php.net/manual/en/mysqli.connect-errno.php), `mysqli_connect_errno()` has never taken a parameter; why is there one in `sqllib.inc.php`? And why has it been there for 9 years and (apparently) never caused problems for anybody else? I’m thoroughly confused.

**Comment by Gargaj** [comment]
PHP8 is not yet supported; it's on my todo list.

**Comment by Bombe** [comment]
Hmm, yeah, I see that, there’s _a lot_ of warnings all through the HTML page… 😀 however, even [in PHP5](https://php-legacy-docs.zend.com/manual/php5/en/mysqli.connect-errno) `mysqli_connect_errno` does not take a parameter. Is that just something that PHP simply ignored back then?

**Comment by Gargaj** [comment]
I guess parameter count may be flexible for marshaled / import functions since the matching is done dynamically. No idea.

**Comment by Bombe** [comment]
Alright, downgrading to PHP 7 for the time being. 🙂

**Comment by Gargaj** [comment]
Mooooooooost of the stuff should be PHP8-friendly now. Comments welcome if not.
